dist: trusty

before_script:
 - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
 - export MAVEN_OPTS="-Xmx2048m"
 - echo $JAVA_TOOL_OPTIONS
 - echo $MAVEN_OPTS

language: java

notifications:
  email:
    recipients:
      - stalk.calvin@gmail.com
    on_success: change
    on_failure: always

jdk:
  - oraclejdk8

env:
  - CODACY_PROJECT_TOKEN=ae6a2f5f152b4f7bbdd99377aa44d28a

before_install:
  - sudo apt-get install jq

script: "mvn clean test jacoco:report coveralls:report"
