before_script:
 - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
 - export MAVEN_OPTS="-Xmx2048m"
 - echo $JAVA_TOOL_OPTIONS
 - echo $MAVEN_OPTS

language: java

jdk:
  - oraclejdk8

script: "mvn clean test"

